### ISSUE TITLE
lon.col and lat.col in Vignette should be x.col and y.col (or vice versa)

### ISSUE THREAD

**Issue by mlammens** [mlammens/spThin#5]
@paleo13 the vignette in your recent push doesn't work because in each example there are argument lon.col and lat.col. In the spThin function, the arguments should be x.col and y.col. My preference is for spThin to have arguments lon.col and lat.col, though I'm not fully married to that idea. Do you have an opinion and how hard of a change will it be to edit spThin, as opposed to the vignette?

**Comment by paleo13** [comment]
Thanks for catching that! 

The reason I was thinking of x.col + y.col vs lon.col + lat.col is because the rarefy method requires a grid to overlay the points. If the points are specified in lon/lats, then the grid would have to be generated using decimal degree units. But this isn't good because the size of a decimal degree in metres changes depending where we are on the planet. So a grid constructed using decimal degrees would have different sized grid cells. IMO, the lon/lat points should be projected to an equal-area coordinate system in metres. Then a grid can be generated such that each grid cell is the same area, and then the points can can be overlayed.

So, while lon/lat points can be passed in and decimal degree grids could be generated, I wanted to discourage this. To do this I:
* made the arguments x.col and y.col and not lon.col and lat.col to suggest that points do not have to be lon/lats.
* included a proj4string argument in spRarefy to project them to a different coordinate system, to make it easier for the user to do this if they are not familiar with GIS operations in R. 
* made the function throw a warning if lon/lat data were passed in.

Unlike spRarefy, spThin can take lon/lat points because it can use great circle distances. This is the default, so I used lon.col and lat.col. This is where it gets confusing I think. 

What do you think if we changed both arguments in both functions to x.col and y.col, and make the defaults for both functions treat them as lon/lat data?

**Comment by mlammens** [comment]
I see your point about the equal size grids. That's something we thought about when comparing spThin to rarification methods while writing the software note. I'm ok switching to x.col and y.col as long as the documentation makes it clear that these can be longitude and latitude values, particularly for spThin.
