### ISSUE TITLE
Why use the phrase "Stingy heuristic algorithm"?

### ISSUE THREAD

**Issue by mlammens** [mlammens/spThin#7]
@paleo13 Stingy has a negative connotation, in general. So why use this term to describe the heuristic algorithm? Is this a common term for such algorithms?

**Comment by paleo13** [comment]
Yeah, a 'stingy heuristic' is the name for an algorithm where you start off with all the 'things' included and iteratively remove 'things' until you reach some stopping criteria. Conversely, a 'greedy heuristic' is where you start off with no 'things' included and iteratively add 'things' until the stopping is reached.

I suspect the negative descriptions for these heuristics is used because they don't guarantee optimality--depending on the problem they can yield results 30% worse than optimality.

I'll make a note of this in the vignette + help files.

**Comment by mlammens** [comment]
I figured it was an algorithm term. Thanks for making the notes.
