### ISSUE TITLE
Stingy algorithm returning unthinned datasets

### ISSUE THREAD

**Issue by mlammens** [mlammens/spThin#9]
@paleo13 I'm testing out the latest pull request. When I run the stingy algorithm the "best thinned dataset" returned has 201 locations - that is, none were removed. When I used the lp_solve method, the "best thinned dataset" contains 123 records. Neither of these match what the original `thin` algorithm produced or the "by hand" method yielded. Any idea what's going wrong?

**Comment by paleo13** [comment]
Regarding lp_solve was this when using code in the vignette or running it using other code? If using the vignette, I set a timeout of 10 seconds, because lp_solve generally takes 10 minutes to run for the built-in dataset. So the solution returned in the vignette is extremely unlikely to be optimal.

Not sure what's going wrong with the stingy aglorithm, I'll take a look this afternoon and get back to you.

**Comment by mlammens** [comment]
That's right, I was using the code in the vignette. If you run lp_solve for longer, do you get to the optimal solution? Also, then we should emphasize that it needs to run longer to achieve the optimal solution.

**Comment by mlammens** [comment]
Fixed with most recent changes by @paleo13
